### ISSUE TITLE
when  the form is the main form ,the noticefication show was not in the application

### ISSUE THREAD

**Issue by yaolc** [AntdUI/AntdUI#1]
![1706521703334](https://github.com/AntdUI/AntdUI/assets/49051136/71aed582-6d1f-4403-9051-d13a30909b91)
and the code is:
  private void button1_Click(object sender, EventArgs e)
  {
      AntdUI.Notification.success((this), "hello","This is a success message");
  }

**Comment by EVA-SS** [comment]
最近访问github比较困难gitee已处理
