### ISSUE TITLE
selectbox no method DataSource and inputBox event KeyPress inactive

### ISSUE THREAD

**Issue by boolinux** [AntdUI/AntdUI#11]
### 版本号

1.3.5.0

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 11

### 如何复现

I cannot use the KeyPress event on inputBox controls and using selectBox will not have the DataSource method

**Comment by EVA-SS** [comment]
If you want to intercept string input, you can refer to the `bool Verify` method in `InputNumber`

https://github.com/AntdUI/AntdUI/blob/2888150280241cb4bbc5a866f3952b3b85acec4e/src/AntdUI/Controls/InputNumber.cs#L209

**Comment by EVA-SS** [comment]
`Select` does not support `DataSource`. This is a purely custom control and does not support some native features. Items are of `object` type, and override `ToString` tells the UI what to display. It is basically universal
