### ISSUE TITLE
请为窗口阴影添加鼠标穿透

### ISSUE THREAD

**Issue by CodeRyn2019** [AntdUI/AntdUI#13]
### 版本号

1.4.3

### .NET SDK

.NET8

### 操作系统

Windows 10

### 如何复现

鼠标点击窗口的阴影时不会穿透

### 截图或视频

![Screenshot 2024-07-08 014650](https://github.com/AntdUI/AntdUI/assets/71699508/5a8add79-29f7-4c4e-a737-3227ff874f15)
点击图片所示的阴影部分时，不会切换到后面窗口

**Comment by EVA-SS** [comment]
Explanation is not rich enough, which class is being used?

**Comment by CodeRyn2019** [comment]
> Explanation is not rich enough, which class is being used?

AntdUI.BorderlessForm

**Comment by EVA-SS** [comment]
This issue is your enhance, not a bug

**Comment by EVA-SS** [comment]
[nuget 1.4.5](https://www.nuget.org/packages/AntdUI/1.4.5) release，`ShadowPierce`

### Properties

Name | Description | Type | Default | Supports DPI|
:--|:--|:--|:--|:--:|
**Resizable** | 调整窗口大小 | bool | true |
**Dark** | 深色模式 | bool | false |
**Mode** | 色彩模式 | [TAMode](Enum#tamode) | Auto ||
**Radius** | 圆角 | int | 0 |✅|
||||
**Shadow** | 阴影大小 | int | 0 |✅|
**ShadowColor** | 阴影颜色 | Color | 100, 0, 0, 0 ||
**ShadowPierce** 🔴 | 鼠标穿透 | bool | false ||
