### ISSUE TITLE
overview 下载时提示病毒

### ISSUE THREAD

**Issue by Charltsing** [AntdUI/AntdUI#14]
chorme 下载刚发布的版本，提示病毒。Windows10 Defender。

![捕获](https://github.com/user-attachments/assets/41a2737a-967a-4a3e-93fe-f19b0baf929d)

但是我自己编译的没有提示。
[net8.0-windows.zip](https://github.com/user-attachments/files/16509665/net8.0-windows.zip)

 现在net8正流行，以后不要用net6了

**Comment by EVA-SS** [comment]
如果是在发布中下载的 OverView，他就是 net 8.0 AOT的产物，至于他为什么报毒，这我无能为力，请提交代码相关的BUG，Demo程序报毒不是我们应该关心的
