### ISSUE TITLE
目前是我看到所有开源里面做的最丝滑好看的。是否可以增加一些其他控件

### ISSUE THREAD

**Issue by MapleJes** [AntdUI/AntdUI#15]
### 你的功能建议是否和某个问题相关？

目前是我看到所有开源里面做的最丝滑好看的。
项目中实用，经常感觉到烦恼的就是布局和表单数据
例如：1、窗体加载子窗体
2、主窗体，分割布局，
3、主菜单
4、还有表格控件
5、datagridview
6、listview

另外是否开源创建一些类似网易云音乐，或者管理系统的demo程序 供大家学习参考。

左侧菜单，右侧主窗体，上下分割，浮动窗体等功能，是否考虑进阶一步，这样就能够适用常规使用了。
如果开源更厉害的一点类似 visual studio 2022 ide的开发布局风格，界面又好看，那就无敌。

### 你希望看到什么解决方案？

作者是否有交流群。

### 你考虑过哪些替代方案？

作者是否有交流群。

### 你有其他上下文或截图吗？

![111](https://github.com/user-attachments/assets/08c19edb-151e-48ce-9868-1aebfd475af5)

他的这个用起来有点硬，Bug也不少，我希望你这边也能复刻一个版本，丝滑，内存开销更小。

**Comment by EVA-SS** [comment]
很高心你能喜欢，你说的应该都包含

1、窗体加载子窗体
> `TopLevel = false` 即可完成，但这与 `UserControl` 拉不开差距

2、主窗体，分割布局，
> 系统自带的布局容器 `TableLayoutPanel` 与 `FlowLayoutPanel` 早已满足各种布局方式 `并且具有极高的性能`，只是需要自己拖，而不是界面库帮你拖 `没有中间商会让你的软件效率更高`

3、主菜单
> [Menu 导航菜单](https://gitee.com/antdui/AntdUI/wikis/%E6%8E%A7%E4%BB%B6/Menu)

4、表格控件
> [Table 表格](https://gitee.com/antdui/AntdUI/wikis/%E6%8E%A7%E4%BB%B6/Table)

5、datagridview
> [Table 表格](https://gitee.com/antdui/AntdUI/wikis/%E6%8E%A7%E4%BB%B6/Table)，AntdUI 是小众界面库，没有那么多人维护，提供的 Table 具有非常多的功能，如果还是不够满足，可搭配其他界面库一起使用

6、listview
> [Tree 树形控件](https://gitee.com/antdui/AntdUI/wikis/%E6%8E%A7%E4%BB%B6/Tree)，这不光可以 用作树/复选框/也可以多行文本+图标显示

-----------------------

群号：328884096 `首页开头/封面有 非常显眼，注意查看`

AntdUI 免费🉑商用，🧙也招募老法师一起维护

**Comment by MapleJes** [comment]
感谢解答！！！

C# winform 可是工控行业的老大哥了，另外是否可以考虑 开发一些工控行业的控件。
工业风，现在市场应用不少。

还有一个建议，能不能整理一份图标库，所有控件标题左右侧等，都附带一个 svg/ico 图标选择。这样自由搭配起来是不是更好看。


https://www.iconfont.cn/collections/index?spm=a313x.home_index.i1.1.58a33a81mhgt9Q
整一份静态资源，可选择。
