### ISSUE TITLE
当Alert设置loop，然后Text设置为“”时，出现死循环

### ISSUE THREAD

**Issue by kingkong-gan** [AntdUI/AntdUI#16]
### 版本号

1.5.2

### .NET SDK

.NET8

### 操作系统

Windows 10

### 如何复现

当Loop=true，Text=""时，会在Alert.cs第458行进入死循环，因为Width = 0，X和Right会始终不变。进而进而死循环阻塞线程

**Comment by EVA-SS** [comment]
[nuget 1.5.3](https://www.nuget.org/packages/AntdUI/1.5.3) 中发布
