### ISSUE TITLE
AOT编译闪退，没有任何错误提示

### ISSUE THREAD

**Issue by cantops** [AntdUI/AntdUI#17]
### 版本号

1.5.4

### .NET SDK

.NET8

### 操作系统

Windows 11

### 如何复现

直接用ChatUI演示项目设置.Net8框架，开启AOT编译，发布后的结果直接闪退，用VS运行倒是正常。
<PublishAot>true</PublishAot>
<_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
<CustomResourceTypesSupport>true</CustomResourceTypesSupport> 
<TargetFramework>net8.0-windows</TargetFramework>

### 截图或视频

![微信截图_20240821104415](https://github.com/user-attachments/assets/7645078c-b894-465d-8fa5-5b5111a40577)

**Comment by EVA-SS** [comment]
详细说，具体点，发布成功，但是运行闪退吗 `rd.xml` 文件与 `WinFormsComInterop` 是否引用，要素不足

**Comment by cantops** [comment]
> 详细说，具体点，发布成功，但是运行闪退吗 `rd.xml` 文件与 `WinFormsComInterop` 是否引用，要素不足

你说的对，我没有引用rd.xml导致的……引用后就可以了。谢谢！
