### ISSUE TITLE
KeyPress是否支持按键事件过滤

### ISSUE THREAD

**Issue by amiron0188** [AntdUI/AntdUI#18]
### 版本号

1.5.6.0

### .NET SDK

.NET Framework 40

### 操作系统

Windows 11

### 你的需求是什么？

```     
 private void input1_KeyPress(object sender, KeyPressEventArgs e)
  {
      e.Handled = true;
  }
```
描述:winform原生的TextBox如此设置时,会过滤掉键盘的输入事件,AntdUI的Input如此设置则不起作用

**Comment by EVA-SS** [comment]
#11 ，你可以参考这个
