### ISSUE TITLE
Adding a "TabMenuVisible" property to the "Tabs" Control

### ISSUE THREAD

**Issue by HDMI88** [AntdUI/AntdUI#2]
Adding a new property to the existing "Tabs" control. The property should meet the following criteria:
Name: TabMenuVisible
Type: bool
Functionality: Hides or shows the tab headers.

Thank you!

**Comment by EVA-SS** [comment]
Sorry, I'm late. I don't quite understand why `Tabs` need to hide headers. You can try other ways. Tabs inherits `System.Windows.Forms.TabControl`, and I may not be able to do anything about it. If you have a good idea, you can tell me

**Comment by HDMI88** [comment]
> Sorry, I'm late. I don't quite understand why `Tabs` need to hide headers. You can try other ways. Tabs inherits `System.Windows.Forms.TabControl`, and I may not be able to do anything about it. If you have a good idea, you can tell me

I understand your hesitation about hiding tab headers. Here's why it might be considered and some alternative approaches:

- Reasons for Hiding Tab Headers:
1. Clean Aesthetics: Simplifying the interface, especially when there are many tabs.
2. Space Saving: Providing more area for the content within each tab.
3. Custom Navigation: Creating unique navigation mechanisms instead of relying solely on headers.

- Alternative Approaches:
1. Dropdown Lists: Replacing headers with a dropdown for selecting tabs.
2. Side Navigation: Arranging tabs vertically for different layouts.
3. Icons: Combining icons with short text labels to improve visual representation.

- Example:
After hiding tab headers, you can use Dropdown Lists, menu controls, or other innovative methods to display tabs.

**Comment by EVA-SS** [comment]
Thank you for the @Aut-Design invaluable assistance; the issue has now been effectively addressed and resolved. [TabMenuVisible](https://github.com/AntdUI/AntdUI/blob/6516a263d7e75312440152121d092c99a02eb2e0/src/AntdUI/Controls/Tabs.cs#L140C21-L140C35)
