### ISSUE TITLE
 AntdUI.ContextMenuStrip 组件初始化时无法设置宽带以及高度、主窗体隐藏时无法触发NotifyIcon组件的点击事件

### ISSUE THREAD

**Issue by NiceTsT** [AntdUI/AntdUI#21]
### 你的功能建议是否和某个问题相关？

不是

### 你希望看到什么解决方案？

可以支持自定义右键菜单栏的宽高，主窗体隐藏时无法触发右键菜单栏展示的替代方案或者封装好

### 你考虑过哪些替代方案？

目前是new 一个UserControl ，然后将其作为新的Control，

### 你有其他上下文或截图吗？

![微信截图_20240905174256](https://github.com/user-attachments/assets/d8a9fe57-5481-450e-9fa1-8c6e91409b34)

**Comment by NiceTsT** [comment]
弹出的右键菜单栏后，需要点击主窗体或者选择菜单栏的功能后，该菜单栏才会隐藏，选择电脑桌面其他地方都不会将其隐藏

**Comment by EVA-SS** [comment]
[nuget 1.5.9](https://www.nuget.org/packages/AntdUI/1.5.9) 中发布

**若依旧存在问题，可重新打开此issue**
