### ISSUE TITLE
richtextbox能否也美化下组件，简单的边框调整和inputs一样也行

### ISSUE THREAD

**Issue by NiceTsT** [AntdUI/AntdUI#22]
### 你的功能建议是否和某个问题相关？

目前可能会开发一些文本功能，富文本框较支持效果比较多，例如可以同时给多个选中的字体上色之类的一些功能

### 你希望看到什么解决方案？

简单的边框样式调整和inputs一样也行，因为我把input 和richbox放一起，richbox的样式显得格格不入。

### 你考虑过哪些替代方案？

暂时没想到，AntUI的样式很好看，没找到如何将richbox调整成一样的样式

### 你有其他上下文或截图吗？

![1725940332274](https://github.com/user-attachments/assets/92e65f84-138f-424f-8b71-6530dfaaa9dc)

**Comment by EVA-SS** [comment]
这对gdi开发来说是毁灭性的工作量，富文本框所有支持的功能，均需要开发，不亚于开发一个md编辑器

**Comment by NiceTsT** [comment]
好的，感谢
