### ISSUE TITLE
windowBar control

### ISSUE THREAD

**Issue by HDMI88** [AntdUI/AntdUI#3]
* Issue:
1. The attributes in the "windowBar" control, such as maximize box, minimize box, close form, sub text, and text automatically center horizontally when the width of the "windowBar" is changed. When the width of the "windowBar" is large, these attributes are located far from the top edge of the form, affecting the aesthetics.
- Proposals: Keep these attributes fixed to the top right corner or the top left corner of the form, regardless of how the width of the "windowBar" changes or add "alignment" property to allow users to align the position of the attributes horizontally (left, center, right) in the "windowBar".

2. When the sub text or text property in the "windowBar" control is left blank, the maximize box, minimize box, and close form do not appear.
- Proposals: Fix this bug to ensure that the functions work properly.

**Comment by EVA-SS** [comment]
I'm not quite clear about the specific issue you've encountered, but perhaps the `example/Overview` or setting `Dock = DockStyle.Top` might assist you. The WindowBar is merely a control and does not inherently concern itself with centering within its container; that's not something it's designed to handle. Rest assured, newer versions have already resolved the issue regarding the non-display of buttons.
