### ISSUE TITLE
AntdUI v1.6.16窗体最小化操作缺陷

### ISSUE THREAD

**Issue by LambertW** [AntdUI/AntdUI#31]
组件，AntdUI.Window
场景，使用pageheader的**最小化**按钮缩小后恢复窗体显示（或在任务栏中点击程序图标缩小，两种形式均可触发），窗体的右边框、下边框会被拉长显示。
重复最小化操作均可复现。

**Comment by EVA-SS** [comment]
你是如何避开模板的，你的issue无效，没有提供任何信息

**Comment by LambertW** [comment]
不好意思，用的手机APP。我重新提交一个
