### ISSUE TITLE
AntdUI窗体最小化操作缺陷

### ISSUE THREAD

**Issue by LambertW** [AntdUI/AntdUI#32]
### Version

V1.6.16

### .NET version

8.0.403

### OS

Windows 10.0.19045

### Steps to reproduce

1. 创建AntdUI.Window窗体
2. 创建pageheader，允许最小化
3. 运行程序，点击**最小化**按钮缩小
4. 恢复窗体显示
5. 窗体的右边框、下边框会被拉长显示。

### Issue description

重复最小化操作均可复现

**Comment by EVA-SS** [comment]
升级 `1.7.0beta` 试试

**Comment by LambertW** [comment]
试了，升级了1.7.0-beta，问题还是存在的。

**Comment by EVA-SS** [comment]
我用release和debug都正常
![ChatUI1](https://github.com/user-attachments/assets/66273720-2ab5-4736-9058-3ffc00ebe1cf)
