### ISSUE TITLE
悬浮按钮鼠标滑过程序异常

### ISSUE THREAD

**Issue by liuubowei** [AntdUI/AntdUI#6]
### 版本号

5.0版本 2024.3.15

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 11

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/AntdUI/AntdUI/issues)

### 如何复现

鼠标滑过悬浮按钮

### 异常信息

System.NullReferenceException:“Object reference not set to an instance of an object.”在Win32.cs 这个函数 internal static void SetBits(Bitmap bitmap, Rectangle rect, IntPtr intPtr, byte a = 255)
       {
           IntPtr oldBits = IntPtr.Zero, screenDC = GetDC(IntPtr.Zero), hBitmap = IntPtr.Zero, memDc = CreateCompatibleDC(screenDC);
           try
           {
               var srcLoc = new Win32Point(0, 0);
               var blendFunc = new BLENDFUNCTION();
               hBitmap = bitmap.GetHbitmap(Color.FromArgb(0));这里异常

### 截图或视频

![image](https://github.com/AntdUI/AntdUI/assets/36073809/883b31e1-8d6f-4526-9b45-47d5b1563385)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护好良好的社区氛围。

**Comment by EVA-SS** [comment]
此问题不必理会，可以过滤，并不会导致程序崩溃
