### ISSUE TITLE
How to make table scale full width parent control

### ISSUE THREAD

**Issue by xuanco941** [AntdUI/AntdUI#7]
### 版本号

1.2.7.0

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 10

### 你的需求是什么？

I want to make this table maximum length in its parent element, please help me

![image](https://github.com/AntdUI/AntdUI/assets/68849866/1fba6d9c-7a4f-4075-8108-fbd99c2ba2f1)

**Comment by EVA-SS** [comment]
`AutoSizeColumnsMode.Fill` has been added in version `1.2.8`  is used to fill when the column width is not enough

**Comment by xuanco941** [comment]
> `AutoSizeColumnsMode.Fill` has been added in version `1.2.8` is used to fill when the column width is not enough

Thank you for your support I have upgraded to version 1.2.8, but I got another error when adding AutoSizeColumnMode.Fill

![image](https://github.com/AntdUI/AntdUI/assets/68849866/e090674d-1439-406b-8045-bd62e14b9a42)

**Comment by xuanco941** [comment]
but when I change it to AutoSizeColumnsMode.Auto it works normally

> This doesn't seem like an issue with the `AntdUI`

**Comment by EVA-SS** [comment]
I can't reproduce the problem. Can you download the source code reference to locate the specific problem

**Comment by EVA-SS** [comment]
It has already been fixed in `1.2.9`

**Comment by xuanco941** [comment]
> It has already been fixed in `1.2.9`

it worked, thank you very much!!!!!
