### ISSUE TITLE
How to change default language to English?

### ISSUE THREAD

**Issue by xuanco941** [AntdUI/AntdUI#8]
### 版本号

1.2.9

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 10

### 你的需求是什么？

Can I change the default language to English or can I customize text in control DatePickerRange and default text on Table?

![image](https://github.com/AntdUI/AntdUI/assets/68849866/ae68e3c4-9f3d-4bc1-89ad-b48b0f4d9ab7)
![image](https://github.com/AntdUI/AntdUI/assets/68849866/fcc7cd1c-1a67-43f1-8790-fe9fd06e001b)

**Comment by EVA-SS** [comment]
[27bcb35](https://github.com/AntdUI/AntdUI/commit/27bcb358e16cbb5f0414d84b7aa011ba0bd6a1c5)，Internationale

```csharp
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            AntdUI.Localization.Provider = new Localizer();
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.Run(new Main());
        }
    }
    public class Localizer : AntdUI.ILocalization
    {
        public string GetLocalizedString(string key)
        {
            switch (key)
            {
                case "Cancel":
                    return "キャンセル";
                case "OK":
                    return "確認";
                case "Now":
                    return "今は";
                case "ToDay":
                    return "今日";
                case "NoData":
                    return "データが一時的にありません";
                case "Year":
                    return "Année";
                case "Month":
                    return "Mois";

                case "Mon":
                    return "Mon";
                case "Tue":
                    return "Tue";
                case "Wed":
                    return "Wed";
                case "Thu":
                    return "Thu";
                case "Fri":
                    return "Fri";
                case "Sat":
                    return "Sat";
                case "Sun":
                    return "Sun";

                default:
                    System.Diagnostics.Debug.WriteLine(key);
                    return key;
            }
        }
    }
```

**Comment by xuanco941** [comment]
> [27bcb35](https://github.com/AntdUI/AntdUI/commit/27bcb358e16cbb5f0414d84b7aa011ba0bd6a1c5)，Internationale
> 
> ```cs
>     internal static class Program
>     {
>         /// <summary>
>         ///  The main entry point for the application.
>         /// </summary>
>         [STAThread]
>         static void Main()
>         {
>             AntdUI.Localization.Provider = new Localizer();
>             Application.SetHighDpiMode(HighDpiMode.SystemAware);
>             Application.Run(new Main());
>         }
>     }
>     public class Localizer : AntdUI.ILocalization
>     {
>         public string GetLocalizedString(string key)
>         {
>             switch (key)
>             {
>                 case "Cancel":
>                     return "キャンセル";
>                 case "OK":
>                     return "確認";
>                 case "Now":
>                     return "今は";
>                 case "ToDay":
>                     return "今日";
>                 case "NoData":
>                     return "データが一時的にありません";
>                 case "Year":
>                     return "Année";
>                 case "Month":
>                     return "Mois";
> 
>                 case "Mon":
>                     return "Mon";
>                 case "Tue":
>                     return "Tue";
>                 case "Wed":
>                     return "Wed";
>                 case "Thu":
>                     return "Thu";
>                 case "Fri":
>                     return "Fri";
>                 case "Sat":
>                     return "Sat";
>                 case "Sun":
>                     return "Sun";
> 
>                 default:
>                     System.Diagnostics.Debug.WriteLine(key);
>                     return key;
>             }
>         }
>     }
> ```

Thank you very much

**Comment by radubprated11** [comment]
<img width="236" height="158" alt="Image" src="https://github.com/user-attachments/assets/0865f8fe-6454-41b8-9568-2628283abda5" />  What key is used to change these Chinese menus?

**Comment by goldorakiller** [comment]
Hello @Eviav 
I can't manage it 
Default
<img width="446" height="357" alt="Image" src="https://github.com/user-attachments/assets/56bc57a8-a28a-4fa2-ad39-7213b6f334f3" />

After
<img width="449" height="368" alt="Image" src="https://github.com/user-attachments/assets/b8b327eb-916e-4b4b-8e6b-3fae802be608" />

With Code

<img width="350" height="564" alt="Image" src="https://github.com/user-attachments/assets/96dee87e-afe8-4a7e-94fa-be4326b2f0e2" />

Thx in advance

**Comment by Eviav** [comment]
@goldorakiller Pay attention to the `AntdUI.ILocalization` class
<img width="381" height="324" alt="Image" src="https://github.com/user-attachments/assets/9cd86121-fea3-47e7-9d1e-a763d581e0ac" />
``` csharp
                case "YearFormat":
                    return "yyyy";
                case "MonthFormat":
                    return "MMM";
```

<img width="660" height="147" alt="Image" src="https://github.com/user-attachments/assets/d409d54b-cb32-4481-ba45-238bbd893476" />

``` csharp
                default:
                    System.Diagnostics.Debug.WriteLine(key);
                    return null;
```
