### ISSUE TITLE
Remove sound from window when modal has MaskClosable = true attribute

### ISSUE THREAD

**Issue by xuanco941** [AntdUI/AntdUI#9]
### 版本号

1.3.0

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 10

### 你的需求是什么？

When using a Modal with the property MaskClosable = true, when clicking on the Mask it makes an annoying noise from the window like when MaskClosable = false, if I click on the close button it doesn't make a sound, I want to use MaskClosable = true but the click no longer causes noise how?

Sorry, there seems to be no sound in my video
https://github.com/AntdUI/AntdUI/assets/68849866/2578fd4a-6bf4-44bf-a0dd-536a4795a9b3

**Comment by EVA-SS** [comment]
Is there a problem with the old version?

**Comment by xuanco941** [comment]
Old versions also have the same problem.

> Is there a problem with the old version?

**Comment by EVA-SS** [comment]
This is built-in to Windows, and I haven't found any way to block it yet

**Comment by xuanco941** [comment]
> This is built-in to Windows, and I haven't found any way to block it yet

Can you try adding this?

    public class Modal : UserControll
    {
        private const int WM_ACTIVATEAPP = 0x001C;

        protected override void WndProc(ref Message m)
        {
            if (m.Msg == WM_ACTIVATEAPP)
            {
                // Suppress the DING sound by not calling the base method
                return;
            }

            base.WndProc(ref m);
        }
    }

**Comment by EVA-SS** [comment]
no working

**Comment by EVA-SS** [comment]
> StackOverflow may be a better place to find answers to this question. WinForms won't want to enable intercepting this noise from our end for accessibility reasons.

https://github.com/dotnet/winforms/issues/11532#issuecomment-2176738473
